<div class="panel-body conteudo">
<div class="conteiner form-group">
		<h3><p class="text-center">Cadastrar Aluno na turma</p></h3><br>
</div>
<div class="conteiner form-group">
	  <div class="col-md-7 col-md-offset-3">
			<?php echo (isset($this->alert) ? $this->alert :"<div class='alert alert-block alert-warning'>
					<h4>Para fazer o cadastro informe a matricula do aluno e defina qual a sala que ele irá estudar!</h4>
					</div>"
				); ?>
              <form action="<?php echo BASE; ?>cadastro/alunoTUrma" class="form-horizontal" method="post">
								<div class="form-group">
									<label for="registration" class="col-sm-2 control-label">Matricula:</label>
                  <div class="col-sm-6">
                    <input required type="numeric" name="registration" class="form-control" id="registration" value="<?php echo $this->request->post('registration') ?>" placeholder="1234567890">
                  </div>
								</div>
								<div class="form-group">
                  <label for="room" name="room" class="col-sm-2 control-label">Turma:</label>
                  <div class="col-sm-6">
                    <select required class="form-control" name="room_id">
                    <option selected="" disabled="">Selecione</option>
                    <?php foreach ($view_room as $room) :
															if($room->status === 1):?>
                        <option value="<?php echo($room->id);?>"><?php echo($room->name.' de '.$room->year.'- Professor: '. $room->teacher);?></option>
                    <?php 		endif;
													endforeach; ?>
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Cadastrar</button>
                  </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
