<div class="panel-body conteudo">
<div class="conteiner form-group">
		<h3><p class="text-center">Cadastrar Atividade</p></h3><br>
</div>
<div class="conteiner form-group">
    <div class="col-md-7 col-md-offset-3">
					<div class="flutuante">
              <?php echo (isset($this->alert) ? $this->alert : '');?>
						</div>
              <form action="<?php echo BASE.'cadastro/atividade/';?>" class="form-horizontal" method="post">
                <div class="form-group">
                  <label for="room" name="room" class="col-sm-2 control-label">Turma:</label>
                  <div class="col-sm-10">
                    <select required class="form-control" name="room_id">
                    <option selected="" disabled="">Selecione</option>
                    <?php  foreach ($view_room as $room) :?>
                        <option value="<?php echo($room->id);?>"><?php echo($room->name.' de '.$room->year.'- Professor: '. $room->teacher);?></option>
                    <?php endforeach; ?>
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label for="subject" class="col-sm-2 control-label">Assunto:</label>
                  <div class="col-sm-10">
                    <input required type="text" name="subject" class="form-control" id="subject" value="<?php echo $this->request->post('subject') ?>" placeholder="Equação do 1 grau">
                  </div>
                </div>
                <div class="form-group">
                  <label for="value" class="col-sm-2 control-label">Valor:</label>
                  <div class="col-sm-10">
                    <input required type="text" name="value" class="form-control" id="value" value="<?php echo $this->request->post('value') ?>" placeholder="10">
                  </div>
                </div>
                <div class="form-group">
                  <label for="date" class="col-sm-2 control-label">Data:</label>
                  <div class="col-sm-10">
                    <input required type="text" name="date" class="form-control" id="date" value="<?php echo $this->request->post('date') ?>" placeholder="02/10/2017">
                  </div>
                </div>
                <!--Falta terminar a parde da data
                /*
                * URGENTE
                */
                -->
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Cadastrar</button>
                  </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
