<div class="panel-body conteudo">
<div class="conteiner form-group">
		<h3><p class="text-center">Cadastrar Turmas</p></h3><br>
</div>
<div class="conteiner form-group">
    <div class="col-md-7 col-md-offset-3">
					<div class="flutuante">
              <?php echo (isset($this->alert) ? $this->alert : '');?>
						</div>
              <form action="<?php echo BASE; ?>cadastro/turma" class="form-horizontal" method="post">
                <div class="form-group">
                  <label for="name" class="col-sm-2 control-label">Nome:</label>
                  <div class="col-sm-10">
                    <input required type="text" name="name" class="form-control" id="name" value="<?php echo $this->request->post('name') ?>" placeholder="1 ano matutino">
                  </div>
                </div>
                <div class="form-group">
                  <label for="name" class="col-sm-2 control-label">Ano</label>
                  <div class="col-sm-10">
                    <input required type="date" name="year" class="form-control" id="year" value="<?php echo $this->request->post('year') ?>" placeholder="2017">
                  </div>
                </div>
                <div class="form-group">
                  <label for="sex" name="sex" class="col-sm-2 control-label">Professor:</label>
                    <div class="col-sm-10">
                      <select required class="form-control" name="teacher">
                      <option selected="" disabled="">Selecione</option>
                      <?php foreach($view_users as $key):
                                if(($key->role_id === 2) &&($key->status === 1)):?>
                                  <option value="<?php echo($key->name);?>"><?php echo($key->name); ?></option>
                        <?php endif;
                            endforeach; ?>
                      </select>
                    </div>
                  </div>
                    <div class="form-group">
                      <label for="sex" name="sex" class="col-sm-2 control-label">Turno:</label>
                      <div class="col-sm-10">
                      <select required class="form-control" name="shift">
                        <option selected="" disabled="">Selecione</option>
                        <option value="Matutino">Matutino</option>
                        <option value="Vespertino">Vespertino</option>
                      </select>
                    </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Cadastrar</button>
                  </div>
                </div>
                </form>
            </div>
        </div>
