<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-heading">
                <a id="logo" href="<?php echo BASE; ?>">
                    <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                </a> <br>
                <?php echo (isset($this->menu) ? $this->menu : ''); ?>
            </div>
            <div class="panel-body">
                <?php echo (isset($this->alert) ? $this->alert : '')?>
              <form action="<?php echo BASE; ?>editar/perfil" class="form-horizontal" method="post">
                <div class="form-group">
                  <label for="registration" class="col-sm-2 control-label">Matricula:</label>
                  <div class="col-sm-10">
                    <input required type="numeric" name="registration" class="form-control" id="registration" value="<?php echo $view_users->registration ?>" placeholder="1234567890">
                  </div>
                </div>
                <div class="form-group">
                  <label for="name" class="col-sm-2 control-label">Nome:</label>
                  <div class="col-sm-10">
                    <input required type="text" name="name" class="form-control" id="name" value="<?php echo $view_users->name ?>" placeholder="João Pedro Costa Da Silva">
                  </div>
                </div>
                <div class="form-group">
                  <label for="username" class="col-sm-2 control-label">Username:</label>
                  <div class="col-sm-10">
                    <input required type="text" name="username" class="form-control" id="username" value="<?php echo $view_users->username ?>" placeholder="João">
                  </div>
                </div>
                <div class="form-group">
                  <label for="birth" class="col-sm-2 control-label">Nascimento:</label>
                  <div class="col-sm-10">
                    <input required type="text" name="birth" class="form-control" id="birth" value="<?php echo $view_users->birth?>" placeholder="05/10/2012">
                  </div>
                </div>
                <div class="form-group">
                  <label for="sex" name="sex" class="col-sm-2 control-label">Sexo:</label>
                    <div class="col-sm-10">
                      <select required class="form-control" name="sex">
                      <option selected="" disabled="">Selecione</option>
                      <option value="Masculino">Masculino</option>
                      <option value="Femenino">Femenino</option>
                      </select>
                    </div>
                </div>
                <div class="form-group">
                  <label for="phone" class="col-sm-2 control-label">Telefone:</label>
                  <div class="col-sm-10">
                    <input  type="text" name="phone" class="form-control" id="phone" value="<?php echo $view_users->phone ?>" placeholder="7734932123">
                  </div>
                </div>
                <div class="form-group">
                  <label for="address" class="col-sm-2 control-label">Endereço:</label>
                  <div class="col-sm-10">
                    <input required type="text" name="address" class="form-control" id="address" value="<?php echo $view_users->address ?>" placeholder="Rua Getulho Vargas, N 123">
                  </div>
                </div>
                <div class="form-group">
                  <label for="email" class="col-sm-2 control-label">E-mail:</label>
                  <div class="col-sm-10">
                    <input  type="email" name="email" class="form-control" id="email"  value="<?php echo $view_users->email ?>" placeholder="seu@email.com.br">
                  </div>
                </div>
              <!--
                <div class="form-group">
                  <label for="password" class="col-sm-2 control-label">Senha:</label>
                  <div class="col-sm-10">
                </div>
                    <input  type="password" name="password" class="form-control" id="password" placeholder="************">
                </div>
              -->
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Atualizar</button>
                  </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
