<div class="panel-body conteudo">
<div class="conteiner form-group">
		<h3><p class="text-center">Mudar a senha</p></h3><br>
</div>
<div class="conteiner form-group">
    <div class="col-md-7 col-md-offset-3">
              <?php echo (isset($this->alert) ? $this->alert : ''); ?>
              <form action="<?php echo BASE; ?>editar/senha" class="form-horizontal" method="post">
                <div class="form-group">
                  <label for="oldpass" class="col-sm-4 control-label">Senha Antiga:</label>
                  <div class="col-sm-8">
                    <input type="password" class="form-control" name="oldpass" id="oldpass" placeholder="**********">
                  </div>
                </div>
                <div class="form-group">
                  <label for="newpass" class="col-sm-4 control-label">Nova senha:</label>
                  <div class="col-sm-8">
                    <input type="password" class="form-control" name="newpass" id="newpass" placeholder="**********">
                  </div>
                </div>
                <div class="form-group">
                  <label for="checkpass" class="col-sm-4 control-label">Repita a senha:</label>
                  <div class="col-sm-8">
                    <input type="password" class="form-control"  name="checkpass" id="checkpass" placeholder="**********">
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Redefinir</button>
                  </div>
                </div>
                </form>
            </div>
        </div>
