<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-heading">
                <a id="logo" href="<?php echo BASE; ?>">
                    <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                </a> <br>
                <?php echo (isset($this->menu) ? $this->menu : ''); ?>
            </div>
            <div class="panel-body">
              <?php echo (isset($this->alert) ? $this->alert : ''); ?>
              <div class="alert alert-block alert-warning">
                  <h4>Informe a matricula que deseja recuperar a senha</4>
                    <h1>Falta consertar os names os ids e o posts</h1>
              </div>
              <form action="<?php echo BASE; ?>login/logar" class="form-horizontal" method="post">
                <div class="form-group">
                  <label for="oldpass" class="col-sm-4 control-label">Senha Antiga:</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control" name="oldpass" id="oldpass" value="<?php echo $this->request->post('oldpass') ?>" placeholder="**********">
                  </div>
                </div>
                <div class="form-group">
                  <label for="newpass" class="col-sm-4 control-label">Nova senha:</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control" name="newpass" id="newpass" value="<?php echo $this->request->post('newpass') ?>" placeholder="**********">
                  </div>
                </div>
                <div class="form-group">
                  <label for="checkpass" name="checkpass" class="col-sm-4 control-label">Repita a senha:</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control" id="checkpass" value="<?php echo $this->request->post('checkpass') ?>" placeholder="**********">
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Redefinir</button>
                  </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
