<div class="panel-body conteudo">
<div class="conteiner form-group">
		<h3><p class="text-center">Atividade Avaliativa</p></h3><br>
</div>
<div class="conteiner form-group">
    <div class="col-md-7 col-md-offset-3">
              <?php echo (isset($this->alert) ? $this->alert : ''); ?>
              <form action="<?php echo BASE . 'questao/avaliacao' ?>" class="form-horizontal" method="post">
                <div class="form-group">
                    <?php
                      $num_questao=1;
											if(!empty($view_question)):
                        foreach ($view_question as $key):
													if($key->activities_id == $view_activity['activities_id']):
                            echo $num_questao. ') '. $key->query.'<br>';
														echo "<label><input type='radio' name='alternative' value='a'> a). $key->alternative_a</label>".'<br>';
														echo "<label><input type='radio' name='alternative' value='b'> b). $key->alternative_b</label>".'<br>';
														echo "<label><input type='radio' name='alternative' value='c'> c). $key->alternative_c</label>".'<br>';
														echo "<label><input type='radio' name='alternative' value='d'> d). $key->alternative_d</label>".'<br>';
														echo "<label><input type='radio' name='alternative' value='e'> e). $key->alternative_e</label>".'<br>';
                          $num_questao++;
												endif;
                        endforeach;
                     ?>
                </div>
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Responder</button>
                    <a href="<?php echo BASE;?>home" class="btn btn-danger">Canselar</a>
                  </div>
                </div>
								<?php endif; ?>
                </form>
            </div>
        </div>
