<script type="text/javascript">
    google.load("visualization", "1", {packages: ["corechart"]});
    //função de monta e desenha o gráfico
    function drawChart() {
        //variavel com armazenamos os dados, um array de array's
        //no qual a primeira posição são os nomes das colunas
        var data = google.visualization.arrayToDataTable([
            ['Questão', 'RD atividade'],
            ['Acertou', <?php echo $view_acertos; ?>],
            ['Errou', <?php echo $view_erros; ?>],
        ]);
        //opções para exibição do gráfico
        var options = {
            title: <?php echo "'".($view_assunto->subject)."'" ; ?>, //titulo do gráfico
            is3D: true // false para 2d e true para 3d o padrão é false
        };
        //cria novo objeto PeiChart que recebe
        //como parâmetro uma div onde o gráfico será desenhado
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        //desenha passando os dados e as opções
        chart.draw(data, options);
    }
    //metodo chamado após o carregamento
    google.setOnLoadCallback(drawChart);
</script>
<div class="panel-body conteudo">
    <div class="form-group">
        
    <h3><p class="text-center">Histórico da atividade</p></h3><br>
    <form action="<?php echo BASE; ?>questao/visualizarHistorico" class="form-horizontal" method="post">
            
            <div class="visualizar">
                   <div class="visualizar" id="chart_div"></div>
            </div>
        </form>
    </div>
</div>
