<div class="panel-body conteudo">
<div class="conteiner form-group">
		<h3><p class="text-center">Listar Turmas</p></h3><br>
</div>
<div class="conteiner form-group">
	<?php
		echo (isset($this->alert) ? $this->alert : '');
	?>
	<div class="col-sm-12">
	<div class="card-box">
	<table id="datatable" class="table table-striped table-bordered">
	<thead>
			<tr>
				<th>ID</th>
				<th>Nome</th>
				<th>Professor</th>
				<th>Ano</th>
				<th>Turno</th>
				<th>Ações</th>
			</tr>
		</thead>
		<tbody>
			<?php
        $id = 1;
				if ($view_room) :
					foreach ($view_room as $room) :
			?>
						<tr>
							<td><?php echo $id; ?></td>
							<td><?php echo $room->name; ?></td>
							<td><?php echo $room->teacher; ?></td>
              <td><?php echo $room->year; ?></td>
              <td><?php echo $room->shift; ?></td>
              <td>
								<?php if ($room->status === 0) : ?>
									<a href="<?php echo BASE . 'sigma/desbloquearTurma/' . $room->id; ?>" class="btn btn-xs btn-success">
										<i class="fa fa-unlock"></i> Abrir
									</a>
								<?php else: ?>
									<a href="<?php echo BASE . 'sigma/bloquearTurma/' . $room->id; ?>" class="btn btn-xs btn-danger">
										<i class="fa fa-lock"></i> Fechar
									</a>
								<?php endif; ?>
							</td>
						</tr>
			<?php
            $id ++;
					endforeach;
				endif;
			?>
		</tbody>
	</table>
</div>
</div>
</div>
</div>
