<div class="panel-body conteudo">
<div class="conteiner form-group">
		<h3><p class="text-center">Lista de Atividades Desenvolvidas</p></h3><br>
</div>
<div class="conteiner form-group">
	<?php
		echo (isset($this->alert) ? $this->alert : '');
	?>
	<div class="col-sm-12">
	<div class="card-box">
	<table id="datatable" class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>ID</th>
				<th>Assunto</th>
				<th>Turma</th>
				<th>Data</th>
				<th>Ações</th>
			</tr>
		</thead>
		<tbody>
			<?php
        $id = 1;

				if ($view_activity) :
					foreach ($view_activity as $activity) :

			?>
						<tr>
							<td><center><?php echo $id; ?></center></td>
							<td><center><?php echo $activity->subject; ?></center></td>
							<td><center><?php echo $activity->rooms_id; ?></center></td>
  						<td><center><?php echo $activity->date; ?></center></td>
							<td>
              	<?php if ($activity->status === 0) : ?>
									<center><a href="<?php echo BASE . 'sigma/desbloquearAtividade/' . $activity->id; ?>" class="btn btn-xs btn-success">
										<i class="fa fa-unlock"></i> Desbloquear
									</a></center>
								<?php else: ?>
									<center><a href="<?php echo BASE . 'sigma/bloquearAtividade/' . $activity->id; ?>" class="btn btn-xs btn-danger">
										<i class="fa fa-lock"></i> Bloquear
									</a></center>
								<?php endif; ?>
							</td>
						</tr>
			<?php
            $id ++;
					endforeach;
				endif;
			?>
		</tbody>
	</table>
</div>
</div>
</div>
