<div class="panel-body conteudo">
<div class="conteiner form-group">
		<h3><p class="text-center">Relatório de Desempenho por Aluno</p></h3><br>
</div>
<div class="conteiner form-group">
	<?php
		echo (isset($this->alert) ? $this->alert : '');
	?>
	<div class="col-sm-12">
	<div class="card-box">
	<table id="datatable" class="table table-striped table-bordered">
	<thead>
			<tr>
				<th>ID</th>
				<th>Matricula</th>
				<th>Nome</th>
				<th>Ações</th>
			</tr>
		</thead>
		<tbody>
			<?php
        $id = 1;
				if ($view_users) :
					foreach ($view_users as $user) :
						if($user->role_id === 3):
			?>
						<tr>
							<td><?php echo $id; ?></td>
							<td><?php echo $user->registration; ?></td>
							<td><?php echo $user->name; ?></td>
							<td>
								<center><a href="<?php echo BASE . 'sigma/visualizarRDAluno/' . $user->id; ?>" class="btn btn-xs btn-success">
									<i class="fa fa-unlock"></i> Visualizar
								</a></center>

							</td>
						</tr>
			<?php
            $id ++;
					endif;
					endforeach;
				endif;
			?>
		</tbody>
	</table>
</div>
</div>
</div>
</div>
