<div class="panel-body conteudo">
  <div class="conteiner form-group">
    <h3><p class="text-center">Visualizar relatório de desempenho por aluno</p></h3><br>
    <form action="<?php echo BASE; ?>sigma/visualizarRDAluno" class="form-horizontal" method="post">
      <div class="form-group">
        <label for="room" name="tipo" class="col-sm-2 control-label">Tipo:</label>
        <div class="col-sm-4">
          <select required class="form-control" name="tipo">
          <option selected="" disabled="">Selecione</option>
              <option value="simples">Simples</option>
              <option value="completo">Completo</option>
          </select>
        </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-3">
              <button type="submit" class="btn btn-success">Visualizar</button>
            </div>
          </div>
      </div>
    </form>
        <?php if(!empty($view_tipo)): ?>
            <?php if($view_tipo['tipo'] == 'simples'): ?>
              <div class="visualizar" id="chart_div"></div>
              <?php endif; ?>
                <?php if($view_tipo['tipo'] == 'completo'): ?>
                    <div class="visualizar" id="barras"></div>
              <?php endif; ?>
        <?php endif; ?>
  </div>
</div>
