<script type="text/javascript">
    google.load("visualization", "1", {packages: ["corechart"]});
    //função de monta e desenha o gráfico
    function drawChart() {
        //variavel com armazenamos os dados, um array de array's
        //no qual a primeira posição são os nomes das colunas
        var data = google.visualization.arrayToDataTable([
            ['Questão', 'Porcentagem'],
            ['Aprovados', <?php echo $view_aprovados; ?>],
            ['Reprovados', <?php echo $view_reprovados; ?>]
        ]);
        //opções para exibição do gráfico
        var options = {
            title: <?php echo "'" . ($view_assunto->subject) . "'"; ?>, //titulo do gráfico
            is3D: true // false para 2d e true para 3d o padrão é false
        };
        //cria novo objeto PeiChart que recebe
        //como parâmetro uma div onde o gráfico será desenhado
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        //desenha passando os dados e as opções
        chart.draw(data, options);
    }
    //metodo chamado após o carregamento
    google.setOnLoadCallback(drawChart);
</script>
<script type="text/javascript">
    google.load("visualization", "1", {packages: ["corechart"]});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
//montando o array com os dados
        var data = google.visualization.arrayToDataTable([
            ['questão', 'Acertos', 'Erros'],
<?php
$aux = 1;
for ($i = 0; $i < $view_total; $i++) {
    if ($aux < $view_total) {
        $x = ',';
    } else {
        $x = NULL;
    }
    echo '[' . "'" . $aux . "'" . ',' . $view_acertos[$i] . ',' . $view_erros[$i] . ']' . "$x";

    $aux++;
}
?>
        ]);
//opçoes para o gráfico barras
        var options = {
            title: <?php echo "'" . ($view_assunto->subject) . "'"; ?>,
            vAxis: {title: 'Questões', titleTextStyle: {color: 'black'}}//legenda vertical
        };
//instanciando e desenhando o gráfico barras
        var barras = new google.visualization.BarChart(document.getElementById('barras'));
        barras.draw(data, options);

    }
</script>
<div class="panel-body conteudo">
    <div class="conteiner form-group">
        <h3><p class="text-center">Visualizar relatório de desempenho por aluno</p></h3><br>
        <form action="<?php echo BASE; ?>sigma/visualizarRDAluno" class="form-horizontal" method="post">
            <div class="form-group">
                <label for="room" name="tipo" class="col-sm-2 control-label">Tipo:</label>
                <div class="col-sm-4">
                    <select required class="form-control" name="tipo">
                        <option selected="" disabled="">Selecione</option>
                        <option value="simples">Simples</option>
                        <option value="completo">Completo</option>
                    </select>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-3">
                        <button type="submit" class="btn btn-success">Visualizar</button>
                    </div>
                </div>
            </div>
        </form>
        <?php if (!empty($view_tipo)): ?>
            <?php if ($view_tipo['tipo'] == 'simples'): ?>
                <div class="visualizar" id="chart_div"></div>
            <?php endif; ?>
            <?php if ($view_tipo['tipo'] == 'completo'): ?>
                <div class="visualizar" id="barras"></div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
