<div class="row">
    <br><br>
    <div class="container">
        <div class="row">
                  <?php echo (isset($this->alert) ? $this->alert : ''); ?>
            <div class="col-sm-6 col-md-4 col-md-offset-4">
                <div class="account-wall">
                    <img class="profile-img" src="<?php echo IMG; ?>sigma-logo.png"
                         alt="">
                    <form action="<?php echo BASE;?>login/logar" class="form-signin" method="post">
                        <input type="text" class="form-control" id="registration" name="registration" placeholder="1234567890" required autofocus>
                        <input type="password" class="form-control" id="password" name="password" placeholder="Senha" required>
                        <button class="btn btn-lg btn-primary btn-block" name="entrar" type="submit">
                            Entrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<br>
<br>
