<!doctype html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Bruno C. Santos">
	<meta name="generator" content="HXPHP Framework">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo $view_title; ?></title>
	<link rel="shortcut icon" href="<?php echo IMG; ?>favicon.jpg" type="image/x-icon">
	<link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">
	<link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css">
	<link rel="stylesheet" href="<?php echo CSS; ?>custom_menu.css" type="text/css">
	<?php
		echo $add_css;
		echo $add_js;
	?>
</head>
<body>
<style>
body {
	padding-top: 4%;
}
</style>
<div class="navbar navbar-default navbar-fixed-top navbar-left" role="navigation">
	<div class="container">
			<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav navbar-right">
							<li><a href="<?php echo BASE;?>login/sair" target="_self">Sair</a></li>
					</ul>
			</div><!--/.nav-collapse -->
	</div>
</div>
<div class="logo-sigma">
	<a id="logo" href="<?php echo BASE; ?>home/">
			<center><img class="logo" src="<?php echo IMG; ?>sigma-logo.png" alt=""></center>
	</a>
</div>
	<nav class="navbar navbar-default sidebar" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuarios <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a>
          <ul class="dropdown-menu forAnimate" role="menu">
            <li><a href="{{URL::to('createusuario')}}">Crear</a></li>
            <li><a href="#">Modificar</a></li>
            <li><a href="#">Reportar</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">Informes</a></li>
          </ul>
        </li>
        <li ><a href="#">Libros<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-th-list"></span></a></li>
        <li ><a href="#">Tags<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-tags"></span></a></li>
      </ul>
    </div>
  </div>
</nav>
	<div class="container">
