<!doctype html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Bruno C. Santos">
	<meta name="generator" content="HXPHP Framework">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo $view_title; ?></title>
	<link rel="shortcut icon" href="<?php echo IMG; ?>favicon.jpg" type="image/x-icon">
	<link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">
	<link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css">
	<link rel="stylesheet" href="<?php echo CSS; ?>custom_menu.css" type="text/css">
	<?php
		echo $add_css;
		echo $add_js;
	?>
</head>
<body>
<style>
</style>
<!--<div class="navbar navbar-default navbar-fixed-top navbar-left" role="navigation">
	<div class="container">
			<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav navbar-right">
							<li><a href="<?php echo BASE;?>login/sair" target="_self">Sair</a></li>
					</ul>
			</div>
	</div>
</div>-->
	<nav class="navbar navbar-default sidebar" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
      <ul class="nav navbar-nav">
				<li class="logo-sigma"><a href="<?php echo BASE;?>home"><center><img class="logo" src="<?php echo IMG; ?>sigma-logo.png" alt=""></center></a></li>
        <li class="active"><a href="<?php echo BASE;?>home">Inicio<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Perfil <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a>
          <ul class="dropdown-menu forAnimate" role="menu">
            <li><a href="<?php echo BASE;?>editar/perfil">Editar</a></li>
            <li><a href="<?php echo BASE;?>editar/senha">Modificar senha</a></li>
            <li class="divider"></li>
            <li><a href="#">Reportar errors</a></li>
          </ul>
        </li>
				<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cadastro <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-th-list"></span></a>
          <ul class="dropdown-menu forAnimate" role="menu">
            <li><a href="<?php echo BASE;?>cadastro/atividade">Atividade</a></li>
	          <li><a href="<?php echo BASE;?>cadastro">Usuario</a></li>
          </ul>
        </li>
				<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">SIGMA <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-gbp"></span></a>
          <ul class="dropdown-menu forAnimate" role="menu">
            <li><a href="#">Listar usuario</a></li>
            <li><a href="#">Relatorio de Desempenho</a></li>
          </ul>
        </li>
        </ul>
    </div>
  </div>
</nav>
	<div class="container">
